In [1]:
import numpy as np

In [2]:
def simplex(A, B, C, X, M):
    # (m,n) = M.shape
    # A = M[2:,0:n-1]
    # # print(A)
    # B = M[2:,n-1]
    # # print(B)
    # C = M[1,0:n-1]
    # # print(C)
    # X = M[0,0:n-1]
    # # print(X)
    while True:
        tgt = np.where(np.abs(A @ X - B) == 0)[0]
        A_tgt = A[tgt]
        utgt = np.where(np.abs(A @ X - B) != 0)[0]
        A_utgt = A[utgt]
        B_utgt = B[utgt]

        Z = -(np.linalg.inv(A_tgt)).T
        costs = Z @ C
        positive_cost_directions = np.where(costs > 0)[0]

        if len(positive_cost_directions) == 0:
            print('Optimal Solution :', X)
            print('Objective Value : ', C @ X)
            return X

        v = Z[positive_cost_directions[0]]

        if len(np.where(np.dot(A, v) > 0)[0]) == 0:
            print('Given LP is Unbounded')
            return None

        n = B_utgt - (A_utgt @ X)
        d = A_utgt @ v
        n = n[np.where(d > 0)[0]]
        d = d[np.where(d > 0)[0]]
        s = n / d
        t = np.min(s[s >= 0])
        X = X + t * v

In [3]:
A = np.array([[2, -1], [1, 2], [-1, 1], [-1, 0], [0, -1]])
B = np.array([4, 9, 3, 0, 0])
C = np.array([2, 5])
X = np.array([2, 0])
M = np.array([[2,0,0],[2,5,0],[2,-1, 4],[1,2,9],[-1,1,3],[-1,0,0],[0,-1,0]])
simplex(A, B, C, X, M)

Optimal Solution : [1. 4.]
Objective Value :  22.0


array([1., 4.])

In [4]:
A = np.array([[1, 1], [3, 7], [-1, 0], [0, -1]])
B = np.array([10, 42, 0, 0])
C = np.array([4, 5])
X = np.array([10, 0])
M = np.array([[10,0,0],[4,5,0],[1,1,10],[3,7,42],[-1,0,0],[0,-1,0]])
simplex(A, B, C, X, M)

Optimal Solution : [7. 3.]
Objective Value :  43.0


array([7., 3.])

In [6]:
A = np.array([[2, 1, 0], [1, 2, -2], [0, 1, 2], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
B = np.array([10, 20, 5, 0, 0, 0])
C = np.array([2, -1, 2])
X = np.array([5, 0, 0])
simplex(A, B, C, X, M)

Optimal Solution : [5.  0.  2.5]
Objective Value :  15.0


array([5. , 0. , 2.5])

In [7]:
A = np.array([[1, -1], [2, -1], [-1, 0], [0, -1]])
B = np.array([10, 40, 0, 0])
C = np.array([2, 1])
X = np.array([10, 0])
simplex(A, B, C, X, M)

Given LP is Unbounded
